MvcApiClientMultiplesRoutes/Models/ErrorViewModel.cs
namespace MvcApiClientMultiplesRoutes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcApiClientMultiplesRoutes/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiClientMultiplesRoutes.Services;
using NugetApiModels.Models;

namespace MvcApiClientMultiplesRoutes.Controllers
{
    public class EmpleadosController : Controller
    {

        private ServiceEmpleados service;

        public EmpleadosController(ServiceEmpleados service)
        {
            this.service = service;
        }
    
        public async Task<IActionResult> Index()
        {
            List<Empleado> empleados = await
                this.service.GetEmpleadosAsync();
            List<string> oficios = await
                this.service.GetOficiosAsync();
            ViewData["OFICIOS"] = oficios;

            return View(empleados);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string oficio)
        {
            List<Empleado> empleados = await
                this.service.GetEmpleadosOficioAsync(oficio);
            List<string> oficios = await
                this.service.GetOficiosAsync();
            ViewData["OFICIOS"] = oficios;
            return View(empleados);
        }

        public async Task<IActionResult> Details(int id)
        {
            Empleado emp = await
                this.service.FindEmpleadoAsync(id);
            return View(emp);
        }
    }
}

MvcApiClientMultiplesRoutes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiClientMultiplesRoutes.Models;
using System.Diagnostics;

namespace MvcApiClientMultiplesRoutes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcApiClientMultiplesRoutes/Views/Empleados/Details.cshtml
@model Empleado

<h1>Detalles del empleado</h1>

<h1>@Model.IdEmpleado, @Model.Apellido</h1>
<h3>@Model.Oficio, @Model.Salario</h3>
<h4>Dept: @Model.Departamento</h4>

<a asp-controller="Empleados"
   asp-action="Index"
   class="btn btn-success">
    Volveer
</a>

MvcApiClientMultiplesRoutes/Views/Empleados/Index.cshtml
@model List<Empleado>
@{
    List<string> oficios = ViewData["OFICIOS"] as List<string>;
}
<h1>Empleados</h1>

<form method="post">
    <select name="oficio" class="form-control">
        @foreach (string o in oficios)
        {
            <option value="@o">@o</option>
        }
    </select>
    <button class="btn btn-success">buscar of</button>
</form>

<table class="table table-dark">
    <thead>
        <tr>
            <th>ID</th>
            <th>APELLIDO</th>
            <th>OFICIO</th>
            <th>SALARIO</th>
            <th>DEPARTAMENTO</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Empleado e in Model)
        {
            <tr>
                <td>@e.IdEmpleado</td>
                <td>@e.Apellido</td>
                <td>@e.Oficio</td>
                <td>@e.Salario</td>
                <td>@e.Departamento</td>
                <td>
                    <a asp-controller="Empleados"
                       asp-action="Details"
                       asp-route-id="@e.IdEmpleado"
                       class="btn btn-success">
                        Ver detalles
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcApiClientMultiplesRoutes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcApiClientMultiplesRoutes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApiClientMultiplesRoutes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcApiClientMultiplesRoutes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApiClientMultiplesRoutes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcApiClientMultiplesRoutes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>